package libcore

import (
	"go/parser"
	"go/token"
	"os"
	"strconv"
	"strings"
	"testing"
)

// gomobileGitModule maps the fork cloned by init.sh to the Go module path its
// generated binding imports. The two forks are source-compatible but ship
// separate copies of internal/mobileinit, so picking the wrong one is not a
// style problem: only the runtime that generated the Java glue gets java_vm
// filled in, and asset.Open on the other one dies inside lockJNI() with
// "no current JVM" -> log.Fatalf -> os.Exit(1), killing :bg ~0.3s after start.
var gomobileGitModule = map[string]string{
	"MatsuriDayo/gomobile": "golang.org/x/mobile",
	"sagernet/gomobile":    "github.com/sagernet/gomobile",
	"google/gomobile":      "golang.org/x/mobile",
	"golang/mobile":        "golang.org/x/mobile",
}

func bindingModulePath(t *testing.T) string {
	t.Helper()
	initScript, err := os.ReadFile("init.sh")
	if err != nil {
		t.Fatal(err)
	}
	const marker = "remote add origin https://github.com/"
	for _, line := range strings.Split(string(initScript), "\n") {
		at := strings.Index(line, marker)
		if at < 0 {
			continue
		}
		repo := strings.TrimSuffix(strings.TrimSpace(line[at+len(marker):]), ".git")
		module, ok := gomobileGitModule[repo]
		if !ok {
			t.Fatalf("unknown gomobile fork %q: add its module path to gomobileGitModule", repo)
		}
		return module
	}
	t.Fatal("init.sh does not clone a gomobile fork; cannot check asset against the binding runtime")
	return ""
}

// TestAndroidAssetMatchesBindingRuntime is the regression guard for the 2026-10-05
// toolchain round trip (36d8bb65b switched the tools to sagernet/gomobile, ad835a0c6
// reverted them to MatsuriDayo/gomobile but left this import behind): the app then
// could not connect at all, because every :bg start self-exited on asset.Open.
func TestAndroidAssetMatchesBindingRuntime(t *testing.T) {
	binding := bindingModulePath(t)

	file, err := parser.ParseFile(token.NewFileSet(), "assets_android.go", nil, parser.ImportsOnly)
	if err != nil {
		t.Fatal(err)
	}
	var assetModule string
	found := false
	for _, spec := range file.Imports {
		path, err := strconv.Unquote(spec.Path.Value)
		if err != nil {
			t.Fatal(err)
		}
		if !strings.HasSuffix(path, "/asset") {
			continue
		}
		assetModule = strings.TrimSuffix(path, "/asset")
		found = true
	}
	if !found {
		t.Fatal("Android asset import is missing")
	}
	if assetModule != binding {
		t.Fatalf("asset uses %q but the binding is generated by %q: two mobileinit copies means asset.Open sees java_vm == NULL and log.Fatalf kills :bg", assetModule, binding)
	}
}
